// This program reads a listing of Pilots & Passengers For the first six Virgin Galactic flights to space, from a text file
// generated by the first part of ths program.
// Then displays the information in a GUI. Along with a Space ship that follows the mouse.
// CSC1301 MW 10-12. CRN:4340
// Project3_AdamAdkins_Part1
// Author: Adam Adkins
// Created: 11/15/2014

import java.util.*;
import java.io.*;
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;


public class Project3_2_AdamAdkins{

  public static String[] showLines(String fileName, int startLine, int endLine)
  {
     String line = null;
     int presentLineNum=0;
     BufferedReader obj=null;
     String[] firstArray=new String[endLine-startLine];
     int count=0;
     
  // Obtain the info from falconPunch.txt
     try
     {
          obj=new BufferedReader(new FileReader(fileName));
          while(presentLineNum<=startLine){
            if(obj.readLine()==null){
                  throw new IOException("No info in file");
            } else { presentLineNum++; } 
          }
                //read until the end 
            while(presentLineNum<=endLine) {
                line = obj.readLine();
                if (line==null) {
                    break;
                }
                firstArray[count] = line;
                count++;
                presentLineNum++;
            }
     }catch(IOException ex)
     {
        System.out.println("Cannot read file.\n" + ex.getMessage());
     }finally
     {
       try
       {
         if(obj!=null)
             obj.close(); 
       } catch (IOException no){}
     }
     return firstArray;
  }
//*******************************************************************************************************************
  public static void main(String[] args)
  {
    final String[] nameDisplay = showLines("falconPunch.txt",1,2);                  // flightNumber1
    final String[] nameDisplay2 = showLines("falconPunch.txt",4,13);                // Ppl list 1
    final String[] nameDisplay3 = showLines("falconPunch.txt",15,16);               // flightNumber2
    final String[] nameDisplay4 = showLines("falconPunch.txt",18,27);               // Ppl list 2
    final String[] nameDisplay5 = showLines("falconPunch.txt",29,30);               // flightNumber3 
    final String[] nameDisplay6 = showLines("falconPunch.txt",32,41);               // Ppl list 3
    final String[] nameDisplay7 = showLines("falconPunch.txt",43,44);               // flightNumber4
    final String[] nameDisplay8 = showLines("falconPunch.txt",46,55);               // Ppl list 4
    final String[] nameDisplay9 = showLines("falconPunch.txt",57,58);               // flightNumber5
    final String[] nameDisplay10 = showLines("falconPunch.txt",60,69);              // Ppl list 5
    final String[] nameDisplay11 = showLines("falconPunch.txt",71,72);              // flightNumber6
    final String[] nameDisplay12 = showLines("falconPunch.txt",74,83);              // Ppl list 6
//******************************************************************************************************************
// Create JFrame
    JFrame frame = new JFrame();
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.setContentPane(new JLabel(new ImageIcon("spaceWhale1.jpg")));
    frame.setTitle("USS Murra");
    frame.setIconImage(Toolkit.getDefaultToolkit().getImage("icon.png"));
    
// Layout
    frame.setLayout(new FlowLayout());
// Bring in the Space Ship!
    frame.add(new starFighter()); 
    
// Panels for the Pilot & Passenger names  
    JPanel firstPanel = new JPanel();
    firstPanel.setPreferredSize(new Dimension(1000, 20));
    firstPanel.setBackground(new Color(120,12,130,100));
    frame.add(firstPanel);
    
    JPanel secondPanel = new JPanel();
    secondPanel.setPreferredSize(new Dimension(1000, 20));
    secondPanel.setBackground(new Color(120,12,130,100));
    frame.add(secondPanel);
    
    JPanel thirdPanel = new JPanel();
    thirdPanel.setPreferredSize(new Dimension(1000,20));
    thirdPanel.setBackground(new Color(120,12,130,100));
    frame.add(thirdPanel);
    
    JPanel fourthPanel = new JPanel();
    fourthPanel.setPreferredSize(new Dimension(1000,20));
    fourthPanel.setBackground(new Color(120,12,130,100));
    frame.add(fourthPanel);
    
    JPanel fifthPanel = new JPanel();
    fifthPanel.setPreferredSize(new Dimension(1000,20));
    fifthPanel.setBackground(new Color(120,12,130,100));
    frame.add(fifthPanel);
    
    JPanel sixthPanel = new JPanel();
    sixthPanel.setPreferredSize(new Dimension(1000,20));
    sixthPanel.setBackground(new Color(120,12,130,100));
    frame.add(sixthPanel);
    
// Labels that are set to the text pulled from falconPunch.txt 
    // One label per flight.
    Font font = new Font("Tahoma", Font.BOLD, 10);
    
    JLabel labelOne = new JLabel();
    labelOne.setFont(font);
    labelOne.setText(Arrays.toString(nameDisplay)+"\t"+Arrays.toString(nameDisplay2));//Printing the people in a flight to this JLabel!
    
    JLabel labelTwo = new JLabel();
    labelTwo.setFont(font);
    labelTwo.setText(Arrays.toString(nameDisplay3)+"\t"+Arrays.toString(nameDisplay4));
    
    JLabel labelThree = new JLabel();
    labelThree.setFont(font);
    labelThree.setText(Arrays.toString(nameDisplay5)+"\t"+Arrays.toString(nameDisplay6));
    
    JLabel labelFour = new JLabel();
    labelFour.setFont(font);
    labelFour.setText(Arrays.toString(nameDisplay7)+"\t"+Arrays.toString(nameDisplay8));
    
    JLabel labelFive = new JLabel();
    labelFive.setFont(font);
    labelFive.setText(Arrays.toString(nameDisplay9)+"\t"+Arrays.toString(nameDisplay10));
    
    JLabel labelSix = new JLabel();
    labelSix.setFont(font);
    labelSix.setText(Arrays.toString(nameDisplay11)+"\t"+Arrays.toString(nameDisplay12));
    
    
// text color    
    labelOne.setForeground(Color.white);
    labelTwo.setForeground(Color.white);
    labelThree.setForeground(Color.white);
    labelFour.setForeground(Color.white);
    labelFive.setForeground(Color.white);
    labelSix.setForeground(Color.white);
    
 // put labels in the panels   
    firstPanel.add(labelOne);
    secondPanel.add(labelTwo);
    thirdPanel.add(labelThree);
    fourthPanel.add(labelFour);
    fifthPanel.add(labelFive);
    sixthPanel.add(labelSix);

// show frame 
    frame.pack();
    frame.setSize(1200, 800);
    frame.setResizable(false);
    frame.setVisible(true);
    }
}
